export const SENSOR_DATA_RECEIVED = 'SENSOR_DATA_RECEIVED';
export const SENSOR_DATA_CHECK = 'SENSOR_DATA_CHECK';
export const DELETE_SENSOR_DATA = 'DELETE_SENSOR_DATA';
export const HOSPITAL_BEDS_UPDATED = 'HOSPITAL_BEDS_UPDATED';
